# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4081a6c172f9c84a7a6718053c5c2e5247ed182bd1fa2392ca157a95edd64a69f8de03c04c1cab16ce4ac3ef5440fa03a93c25b90ed07f83f5db9a44ed9ec729

test:
  secret_key_base: f63daad8b673c647d27ee687eb05ed080b0b1ab379081e19d95eacadbc2ccf8985d035a11b668c936ef36b2371fccae906ff39f941dcf2ab59e5253dd8cee01e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
